runtime: python312
entrypoint: gunicorn -b :$PORT app.main:app

env_variables:
  FLASK_ENV: production
  GCS_BUCKET: gray-to-green-uploads
  GOOGLE_CALENDAR_ID: cnelsoncramer@gmail.com

handlers:
  - url: /static
    static_dir: app/static
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 5
